# NOTE: deploy
# docker node update --label-add proxy=true <NODE-NAME>

services:
  proxy:
    image: ghcr.io/zerocluster/proxy
    # depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: run

    secrets:
      - { source: proxy_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

secrets:
  proxy_env.yaml: { file: env.yaml }

networks:
  network: ~
